const motivosMapeados = [{"motivo": "Usar distintivos, insígnias, símbolos ou tarjetas indevidos", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "1", "classificacao": "Leve"}, 
    {"motivo": "Fazer qualquer tipo de marca (externamente) na(s) peça(s) do uniforme de maneira que fique diferente do previsto no regulamento de uniformes", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "2", "classificacao": "Leve"}, 
    {"motivo": "Usar óculos esportivos (escuros ou similares) ou outros adornos não previstos no Regulamento de Uniformes, quando fardado", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "3", "classificacao": "Leve"}, 
    {"motivo": "Trocar de uniforme em local não apropriado", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "4", "classificacao": "Leve"}, 
    {"motivo": "Ingressar nas dependências do Colégio sem estar devidamente uniformizado", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "5", "classificacao": "Leve"}, 
    {"motivo": "Usar o uniforme faltando quaisquer de suas peças (tarjeta, distintivos de bolso, de boina ou série, entre outras) ou usando as mesmas de forma inapropriada dentro ou fora do Colégio", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "6", "classificacao": "Leve"}, 
    {"motivo": "Apresentar-se para as atividades escolares demonstrando não cuidar do asseio próprio ou em condições que, de qualquer forma, contrarie os padrões estabelecidos pelo Colégio tais como uniforme sujo, amassado, amarrotado e outros", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "7", "classificacao": "Leve"},
    {"motivo": "Usar as instalações ou equipamentos esportivos do Colégio sem estar apropriadamente uniformizado", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "8", "classificacao": "Leve"}, 
    {"motivo": "Escrever, desenhar e carimbar em qualquer parte visível do corpo objetos e outras grafias, hennas ou imagens afins", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "9", "classificacao": "Leve"}, 
    {"motivo": "Mexer-se ou conversar excessivamente, quando em forma", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "10", "classificacao": "Leve"}, 
    {"motivo": "Utilizar-se, durante a aula, de qualquer publicação estranha a sua atividade escolar", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "11", "classificacao": "Leve"}, 
    {"motivo": "Tomar parte em jogos proibidos ou em apostas no interior do Colégio", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "12", "classificacao": "Leve"}, 
    {"motivo": "Permanecer fora da sala de aula sem autorização", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "13", "classificacao": "Leve"}, 
    {"motivo": "Usar as instalações ou equipamentos esportivos do Colégio sem a devida autorização", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "14", "classificacao": "Leve"}, 
    {"motivo": "Executar toques ou sinais regulamentares, sem ordem para tal", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "15", "classificacao": "Leve"},
    {"motivo": "Entrar ou sair de local onde estejam presentes todos os elencados no §1º, art. 5º, sem a devida permissão regulamentar", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "16", "classificacao": "Leve"}, 
    {"motivo": "Deixar de realizar tarefa escolar sem motivo justificável", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "17", "classificacao": "Leve"}, 
    {"motivo": "Consumir alimentos, balas, doces ou mascar chicletes durante as atividades escolares ou nas dependências de qualquer seção do Colégio, salvo quando devidamente autorizado", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "18", "classificacao": "Leve"}, 
    {"motivo": "Não apresentar material escolar pré-determinado", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "19", "classificacao": "Leve"}, 
    {"motivo": "Portar telefone celular ou qualquer outro aparelho eletrônico sobreposto ao uniforme", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "20", "classificacao": "Leve"}, 
    {"motivo": "Comercializar qualquer produto no colégio, divulgar impressos, promover rifas, convites, dentre outros, sem autorização", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "21", "classificacao": "Leve"}, 
    {"motivo": "Utilizar as dependências do CMDPII/CBMAC como espaço para namoro", "artigo": "Art. 54", "paragrafo": "§ 1º", "inciso": "22", "classificacao": "Leve"}, 
    {"motivo": "Apresentar-se com o cabelo em desalinho ou fora do padrão estabelecido pelo Colégio", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "1", "classificacao": "Médio"}, 
    {"motivo": "Sair de forma sem permissão de quem de direito", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "2", "classificacao": "Médio"}, 
    {"motivo": "Portar-se de maneira desrespeitosa ou inconveniente durante a aula ou qualquer atividade escolar", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "3", "classificacao": "Médio"}, 
    {"motivo": "Usar telefone celular ou qualquer outro aparelho eletrônico durante a aula ou qualquer outra atividade escolar, sem autorização", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "4", "classificacao": "Médio"}, 
    {"motivo": "Captar imagem ou áudio de alunos, servidores ou das dependências do Colégio, sem autorização da Direção", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "5", "classificacao": "Médio"},
    {"motivo": "Publicar imagens, áudio ou qualquer tipo de publicação em qualquer meio de comunicação referente ao Colégio, servidores ou alunos, sem autorização da Direção", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "6", "classificacao": "Médio"}, 
    {"motivo": "Deixar de entregar ao pai ou responsável documento que lhe foi encaminhado pelo Colégio", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "7", "classificacao": "Médio"}, 
    {"motivo": "Deixar de devolver, no prazo fixado, comunicados, avisos ou outros documentos emitidos pelo Colégio", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "8", "classificacao": "Médio"}, 
    {"motivo": "Chegar atrasado à aula, formatura, atividade, ou qualquer evento fora do colégio", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "9", "classificacao": "Médio"}, 
    {"motivo": "Perturbar, com conversas paralelas, ruídos ou brincadeiras, o desenvolvimento da aula ou de estudo dos colegas", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "10", "classificacao": "Médio"}, 
    {"motivo": "Utilizar-se do anonimato na divulgação de cartas, bilhetes, impressos ou qualquer meio de divulgação, com o intuito de denegrir a imagem do Colégio, dos colegas ou dos servidores", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "11", "classificacao": "Médio"}, 
    {"motivo": "Abandonar, injustificadamente, atividade escolar de que participava", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "12", "classificacao": "Médio"}, 
    {"motivo": "Danificar ou perder material pertencente ao Colégio, servidor ou outro aluno", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "13", "classificacao": "Médio"}, 
    {"motivo": "Deixar de entregar na sala do Comando do Corpo de Alunos, qualquer objeto que não lhe pertença e que tenha encontrado no Colégio", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "14", "classificacao": "Médio"}, 
    {"motivo": "Portar-se de maneira desrespeitosa ou inconveniente nos eventos sociais ou esportivos promovidos no Colégio ou fora dele", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "15", "classificacao": "Médio"}, 
    {"motivo": "Deixar de executar atribuições recebidas da Direção, Corpo de Alunos ou Monitoria", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "16", "classificacao": "Médio"}, 
    {"motivo": "Retirar-se das dependências do CMDPII/CBMAC antes do término das aulas ou de outra atividade, sem permissão de quem de direito", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "17", "classificacao": "Médio"}, 
    {"motivo": "Concorrer para a discórdia, desarmonia ou cultivar inimizade entre colegas ou profissionais do Colégio", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "18", "classificacao": "Médio"}, 
    {"motivo": "Faltar a qualquer escala de representação do CMDPII/CBMAC", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "19", "classificacao": "Médio"}, 
    {"motivo": "Estar realizando atividade diversa da aula no momento lecionada", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "20", "classificacao": "Médio"}, 
    {"motivo": "Rasurar ou amassar documentos (provas, avisos, N.M.D, panfletos, folders entre outros)", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "21", "classificacao": "Médio"}, 
    {"motivo": "Danificar e/ou não devolver os livros do acervo da biblioteca do colégio", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "22", "classificacao": "Médio"}, 
    {"motivo": "Fazer uso de material sem fins pedagógicos (Celular, Revistas, Mini game, Tablet, Smartphone dentre outros aparelhos eletrônicos) dentro ou fora da sala de aula, salvo devidamente autorizado", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "23", "classificacao": "Médio"}, 
    {"motivo": "Dirigir-se, referir-se ou responder ao professor ou funcionários do Colégio, de modo desrespeitoso ou desatencioso", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "24", "classificacao": "Médio"}, 
    {"motivo": "Sair da sala de aula sem permissão de quem de direito", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "25", "classificacao": "Médio"}, 
    {"motivo": "Transitar ou fazer uso das vias de acesso não permitidas aos alunos", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "26", "classificacao": "Médio"}, 
    {"motivo": "Deixar de prestar os sinais de deferência a qualquer servidor, militar ou civil e aos demais alunos", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "27", "classificacao": "Médio"}, 
    {"motivo": "Proferir palavras ofensivas ou grafá-las em qualquer lugar", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "28", "classificacao": "Médio"}, 
    {"motivo": "Ofender a moral por atos, gestos ou palavras", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "29", "classificacao": "Médio"}, 
    {"motivo": "Esquecer material didático, parte do uniforme ou qualquer outro objeto de uso individual", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "30", "classificacao": "Médio"}, 
    {"motivo": "Faltar a qualquer aula ou formatura, estando no Colégio", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "31", "classificacao": "Médio"},
    {"motivo": "Fazer uso do uniforme do colégio, com acessórios não previstos na norma legal...", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "32", "classificacao": "Médio"}, 
    {"motivo": "Faltar a qualquer formatura ou atividade para a qual tenha sido voluntário", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "33", "classificacao": "Médio"}, 
    {"motivo": "Promover algazarra no recinto do Colégio ou fora dele, enquanto uniformizado", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "34", "classificacao": "Médio"}, 
    {"motivo": "Contribuir para má apresentação da sala de aula, atirar papeis, resto de comida ou qualquer objeto no pátio ou fora dos locais destinados a coleta de lixo", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "35", "classificacao": "Médio"},
    {"motivo": "Não cortar o cabelo nas inspeções previstas, tanto para os segmentos masculino quanto feminino", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "36", "classificacao": "Médio"}, 
    {"motivo": "Usar prendedor de cabelo de cor diferente do previsto pelo Colégio", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "37", "classificacao": "Médio"}, 
    {"motivo": "Faltar a qualquer aula ou formatura", "artigo": "Art. 54", "paragrafo": "§ 2º", "inciso": "38", "classificacao": "Médio"}, 
    {"motivo": "Faltar com a verdade", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "1", "classificacao": "Grave"}, 
    {"motivo": "Discutir, desobedecer ou resistir ao atendimento de ordens", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "2", "classificacao": "Grave"}, 
    {"motivo": "Fazer apologia a qualquer fato que constitua crime ou contravenção", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "3", "classificacao": "Grave"}, 
    {"motivo": "Dirigir-se ou referir-se a qualquer servidor, militar ou civil e aos demais alunos usando apelidos ou palavrões", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "4", "classificacao": "Grave"}, 
    {"motivo": "Usar o nome do Colégio para qualquer tipo de propaganda, campanha ou promoção, sem autorização expressa da Direção", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "5", "classificacao": "Grave"}, 
    {"motivo": "Praticar gestos obscenos dentro ou fora do Colégio", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "6", "classificacao": "Grave"}, 
    {"motivo": "Não ter o devido respeito para com os símbolos nacionais", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "7", "classificacao": "Grave"}, 
    {"motivo": "Faltar ao desfile cívico de 07 de setembro sem justificativa", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "8", "classificacao": "Grave"}, 
    {"motivo": "Não manter a compostura quando estiver participando ou representando a qualquer evento realizado pelo CMDPII/CBMAC", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "9", "classificacao": "Grave"}, 
    {"motivo": "Agredir moralmente a qualquer servidor militar ou civil, bem como qualquer aluno do Colégio utilizando-se das redes sociais pela internet ou outro meio de comunicação", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "10", "classificacao": "Grave"}, 
    {"motivo": "Espalhar boatos ou notícias tendenciosas, causando constrangimento a outro aluno ou a qualquer servidor do Colégio", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "11", "classificacao": "Grave"}, 
    {"motivo": "Ausentar-se do Colégio em horário de sua atividade escolar sem autorização", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "12", "classificacao": "Grave"}, 
    {"motivo": "Praticar brincadeiras que possam causar danos psíquicos ou físicos a outro aluno", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "13", "classificacao": "Grave"}, 
    {"motivo": "Portar, introduzir, ler ou distribuir, dentro do Colégio ou nas suas imediações, publicações, estampas ou jornais que atentem contra a disciplina, a moral e aos bons costumes", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "14", "classificacao": "Grave"}, 
    {"motivo": "Promover ou tomar parte em qualquer manifestação coletiva seja de caráter reivindicatório ou político-partidário, quando fardado ou representando o Colégio", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "15", "classificacao": "Grave"},
    {"motivo": "Comunicar-se com outro aluno ou utilizar-se de qualquer meio não permitido durante as provas", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "16", "classificacao": "Grave"}, 
    {"motivo": "Sujar ou danificar deliberadamente as dependências ou bens pertencentes ao Colégio", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "17", "classificacao": "Grave"}, 
    {"motivo": "Incitar briga no interior ou fora do colégio", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "18", "classificacao": "Grave"}, 
    {"motivo": "Deixar de comunicar à Coordenação do Corpo de Alunos de qualquer ato de indisciplina que tenha visto sido praticado por outro aluno do CMDPII/CBMAC", "artigo": "Art. 54", "paragrafo": "§ 3º", "inciso": "19", "classificacao": "Grave"}, 
    {"motivo": "Portar estiletes, seringas, tesoura de ponta, canivete ou qualquer outro tipo de material que possa atentar contra a segurança do Colégio, sem a devida autorização do C.A.", "artigo": "Art. 54", "paragrafo": "§ 4º", "inciso": "1", "classificacao": "Gravíssimo"}, 
    {"motivo": "Portar, introduzir ou fazer uso de qualquer tipo de bebida alcoólica, fumar ou portar cigarro ou droga ilícita no interior do Colégio", "artigo": "Art. 54", "paragrafo": "§ 4º", "inciso": "2", "classificacao": "Gravíssimo"}, 
    {"motivo": "Valer-se de meios ilícitos ou fraudulentos para a resolução dos trabalhos escolares e provas", "artigo": "Art. 54", "paragrafo": "§ 4º", "inciso": "3", "classificacao": "Gravíssimo"}, 
    {"motivo": "Violar ou adulterar documentos emitidos pelo Colégio, assim como atestados médicos, declarações ou qualquer outro documento que tenha fé pública", "artigo": "Art. 54", "paragrafo": "§ 4º", "inciso": "4", "classificacao": "Gravíssimo"},
    {"motivo": "Agredir fisicamente outro aluno ou qualquer servidor do Colégio, militar ou civil", "artigo": "Art. 54", "paragrafo": "§ 4º", "inciso": "5", "classificacao": "Gravíssimo"}, 
    {"motivo": "Praticar qualquer ato infracional ou crime, estando ou não no interior do Colégio", "artigo": "Art. 54", "paragrafo": "§ 4º", "inciso": "6", "classificacao": "Gravíssimo"}, 
    {"motivo": "Comparecer ao colégio ou a qualquer atividade escolar em estado de embriaguez alcoólica ou sob efeito de substância entorpecente", "artigo": "Art. 54", "paragrafo": "§ 4º", "inciso": "7", "classificacao": "Gravíssimo"}, 
    {"motivo": "Falsificar assinatura ou rubrica dos pais/responsável ou de qualquer outra pessoa", "artigo": "Art. 54", "paragrafo": "§ 4º", "inciso": "8", "classificacao": "Gravíssimo"}, 
    {"motivo": "Praticar bullying contra seus colegas de classe, ou contra qualquer outro discente do CMDPII/CBMAC", "artigo": "Art. 54", "paragrafo": "§ 4º", "inciso": "9", "classificacao": "Gravíssimo"}];

function obterDadosDoRegulamento(motivo) {
  const normalizado = motivo.trim().toLowerCase();
  return motivosMapeados.find(m => m.motivo.trim().toLowerCase() === normalizado) || {
    artigo: '',
    inciso: '',
    paragrafo: '',
    classificacao: ''
  };
}
function listarTodosMotivos() {
  return motivosMapeados;
}
module.exports = {
  obterDadosDoRegulamento,
  listarTodosMotivos
};
